# Generated by Django 6.0.3 on 2026-04-24 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stokeitem',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='stokeitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stoke_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
