# Generated by Django 5.2.13 on 2026-05-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('user', '0007_usermodel_branch_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='branch_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='user.branchprofile'),
        ),
    ]
