# Generated by Django 6.0.3 on 2026-04-17 09:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ListOfIngridients', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=17)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(max_length=50)),
                ('advance_amount', models.CharField(blank=True, max_length=150, null=True)),
                ('advance_payment_mode', models.CharField(blank=True, choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('BANK_TRANSFER', 'BANK TRANSFER'), ('ONLINE', 'ONLINE'), ('OTHER', 'OTHER')], max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_time', models.CharField(max_length=100)),
                ('event_address', models.TextField(blank=True)),
                ('per_dish_amount', models.CharField(blank=True, max_length=150, null=True)),
                ('estimated_persons', models.CharField(blank=True, max_length=150, null=True)),
                ('selected_items', models.JSONField(default=dict)),
                ('extra_service_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('extra_service', models.JSONField(default=dict)),
                ('waiter_service_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('waiter_service', models.JSONField(blank=True, default=dict)),
                ('assigned_vendors', models.JSONField(blank=True, default=dict)),
                ('outsourced_items', models.JSONField(blank=True, default=list)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='eventbooking.eventbooking')),
            ],
            options={
                'ordering': ['event_date', 'event_time'],
            },
        ),
        migrations.CreateModel(
            name='EventItemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('is_vendor_supplied', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('calculated_from_persons', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_configs', to='eventbooking.eventbooking')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_event_items', to='vendor.vendor')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_configs', to='eventbooking.eventsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'item_name')},
            },
        ),
        migrations.CreateModel(
            name='IngredientVendorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('item', 'Item'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_vendor_assignments', to='eventbooking.eventbooking')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to='ListOfIngridients.ingridientsitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_vendor_assignments', to='eventbooking.eventsession')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_ingredients', to='vendor.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ingredient', 'session')},
            },
        ),
    ]
