# Generated by Django 6.0.3 on 2026-04-24 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0003_eventbooking_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventbooking',
            index=models.Index(fields=['status'], name='eventbookin_status_16d87c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventbooking',
            index=models.Index(fields=['-date'], name='eventbookin_date_b5f891_idx'),
        ),
    ]
