# Generated by Django 5.2.13 on 2026-05-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0005_session_checklist_tick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionchecklisttick',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
