# Generated by Django 5.2.13 on 2026-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0007_backfill_vendor_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionchecklisttick',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sessionchecklisttick',
            name='action',
            field=models.CharField(choices=[('prepared', 'Prepared'), ('served', 'Served'), ('received', 'Received'), ('delivered', 'Delivered'), ('available', 'Available'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionchecklisttick',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
