# Generated by Django 5.2.13 on 2026-05-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0006_alter_sessionchecklisttick_id'),
        ('eventbooking', '0008_sessionchecklisttick_notes_and_more'),
    ]

    operations = [
    ]
