# Generated by Django 5.1.4 on 2026-04-20 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventbooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroundChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(default='Nos', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ground_items', to='groundmanagement.groundcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroundChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='groundmanagement.groundchecklisttemplate')),
                ('ground_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_requirements', to='groundmanagement.grounditem')),
            ],
            options={
                'ordering': ['template', 'ground_item'],
            },
        ),
        migrations.CreateModel(
            name='EventGroundRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arranged_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_required', models.BooleanField(default=True)),
                ('is_arranged', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_requirements', to='eventbooking.eventbooking')),
                ('event_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_requirements', to='eventbooking.eventsession')),
                ('ground_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_requirements', to='groundmanagement.grounditem')),
            ],
            options={
                'ordering': ['event_session', 'ground_item'],
            },
        ),
        migrations.AddConstraint(
            model_name='grounditem',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_ground_item_per_category'),
        ),
        migrations.AddConstraint(
            model_name='groundchecklisttemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'ground_item'), name='unique_ground_item_per_template'),
        ),
        migrations.AddConstraint(
            model_name='eventgroundrequirement',
            constraint=models.UniqueConstraint(fields=('event_booking', 'event_session', 'ground_item'), name='unique_ground_requirement_per_event_session_item'),
        ),
    ]
