# Generated by Django 5.2.13 on 2026-04-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='included_modules',
            field=models.ManyToManyField(blank=True, help_text='Modules every Client on this plan automatically gets.', related_name='plans', to='accesscontrol.permissionmodule'),
        ),
    ]
