# Generated by Django 5.2.13 on 2026-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_subscriptionplan_included_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
