# Generated by Django 5.1.4 on 2026-04-20 07:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('address', models.TextField()),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='GST number must be 15 characters, start with 2 digits, and contain only letters and numbers.', regex='^[0-9]{2}[A-Z0-9]{13}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'branch_format',
                'ordering': ['branch_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_hsn_code', models.CharField(default='996331', max_length=10)),
                ('available_gst_percentages', models.CharField(default='0,5,12,18,28', max_length=50)),
                ('default_gst_percentage', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('party_gst_no', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='GST number must be 15 characters, start with 2 digits, and contain only letters and numbers.', regex='^[0-9]{2}[A-Z0-9]{13}$')])),
                ('party_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('invoice_prefix', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('next_sequence_no', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'party_information',
                'ordering': ['party_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BranchBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('order_date', models.DateField()),
                ('hsn_code', models.CharField(blank=True, max_length=10, null=True)),
                ('refrance', models.TextField(blank=True, null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('output_sgst_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('output_cgst_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('final_payable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='branchmanagement.branchformat')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_bills', to='branchmanagement.partyinformation')),
            ],
            options={
                'db_table': 'branch_bill',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BranchBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='branchmanagement.branchformat')),
            ],
            options={
                'db_table': 'branch_bank_details',
            },
        ),
        migrations.CreateModel(
            name='BranchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_items', to='branchmanagement.branchformat')),
            ],
            options={
                'db_table': 'branch_item',
                'ordering': ['name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BranchBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_rate_inclusive', models.BooleanField(default=False)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='branchmanagement.branchbill')),
                ('branch_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='branchmanagement.branchitem')),
            ],
            options={
                'db_table': 'branch_bill_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
