# Generated by Django 5.2.13 on 2026-04-29 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFormatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('html_content', models.TextField(help_text='HTML template stored in the database for PDF rendering or preview.')),
                ('sample_data', models.JSONField(blank=True, default=dict, help_text='Optional sample/context data for frontend preview or PDF rendering.')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_formatters_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_formatter',
                'ordering': ['name', 'id'],
            },
        ),
    ]
