# Generated by Django 5.2.13 on 2026-05-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListOfIngridients', '0001_initial'),
        ('user', '0007_usermodel_branch_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingridientscategory',
            name='branch_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_categories', to='user.branchprofile'),
        ),
        migrations.AddField(
            model_name='ingridientsitem',
            name='branch_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_items', to='user.branchprofile'),
        ),
        migrations.AlterField(
            model_name='ingridientscategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingridientsitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
