# Generated by Django 6.0.3 on 2026-04-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_businessprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='color_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Color Code'),
        ),
    ]
