# Generated by Django 5.2.13 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_subscriptionplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="selected_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("gu", "Gujarati"),
                    ("hi", "Hindi"),
                ],
                default="en",
                max_length=10,
                verbose_name="Selected Language",
            ),
        ),
    ]
