# Generated by Django 5.2.13 on 2026-05-07 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_businessprofile_selected_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Branch Name')),
                ('branch_code', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='Branch Code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main Branch')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branches', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch Profile',
                'verbose_name_plural': 'Branch Profiles',
                'db_table': 'BranchProfile',
                'ordering': ('-is_main', 'city', 'name'),
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='branch_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user.branchprofile'),
        ),
        migrations.AddConstraint(
            model_name='branchprofile',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='unique_branch_profile_name_city'),
        ),
    ]
