# Generated by Django 5.2.13 on 2026-05-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_branchprofile_usermodel_branch_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='branch_role',
            field=models.CharField(choices=[('main_admin', 'Main Tenant Admin'), ('branch_admin', 'Branch Admin'), ('branch_user', 'Branch User')], default='branch_user', max_length=30),
        ),
    ]
