# Generated by Django 6.0.3 on 2026-04-17 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventbooking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Role Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Role',
                'verbose_name_plural': 'Staff Roles',
            },
        ),
        migrations.CreateModel(
            name='WaiterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Waiter Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('per_person_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Default per person rate for this waiter type', max_digits=10, verbose_name='Per Person Rate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Waiter Type',
                'verbose_name_plural': 'Waiter Types',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Staff Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('staff_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Agency', 'Agency'), ('Contract', 'Contract')], default='Contract', max_length=20, verbose_name='Staff Type')),
                ('fixed_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fixed Salary')),
                ('per_person_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paid Per Person (Rate)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('joining_date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='Joining Date')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_account', models.OneToOneField(blank=True, help_text='Optional login account for this staff member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Login User')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eventstaff.staffrole', verbose_name='Role')),
                ('waiter_type', models.ForeignKey(blank=True, help_text='Type of waiter service (VIP, VVIP, Normal, Special Couple, etc)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventstaff.waitertype', verbose_name='Waiter Type')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff Members',
            },
        ),
        migrations.CreateModel(
            name='FixedStaffSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='End Date')),
                ('months_count', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Months Count')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Monthly Salary')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Total Gross Amount')),
                ('withdrawal_deduction', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Withdrawal Deduction')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Final Paid Amount')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Remaining Amount')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', editable=False, max_length=20, verbose_name='Payment Status')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(limit_choices_to={'staff_type': 'Fixed'}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='eventstaff.staff', verbose_name='Fixed Staff')),
            ],
            options={
                'verbose_name': 'Fixed Staff Salary Payment',
                'verbose_name_plural': 'Fixed Staff Salary Payments',
                'ordering': ('-start_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='StaffWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Withdrawal Amount')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_adjusted', models.BooleanField(default=False, verbose_name='Adjusted in Salary?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjusted_in_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_withdrawals', to='eventstaff.fixedstaffsalarypayment')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='eventstaff.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Staff Withdrawal',
                'verbose_name_plural': 'Staff Withdrawals',
                'ordering': ('-payment_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EventStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.DecimalField(decimal_places=1, default=1.0, max_digits=5, verbose_name='Total Days')),
                ('number_of_persons', models.PositiveIntegerField(default=1, help_text='Number of staff members supplied by agency/contractor', verbose_name='Number of Persons')),
                ('per_person_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use staff's default rate", max_digits=10, null=True, verbose_name='Per Person Rate (Override)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Total Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paid Amount')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Remaining Amount')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', editable=False, max_length=20, verbose_name='Payment Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='eventbooking.eventsession', verbose_name='Session')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='eventstaff.staff', verbose_name='Staff')),
                ('role_at_event', models.ForeignKey(blank=True, help_text='Override default role for this specific event if needed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventstaff.staffrole', verbose_name='Role at Event')),
            ],
            options={
                'verbose_name': 'Event Staff Assignment',
                'verbose_name_plural': 'Event Staff Assignments',
                'unique_together': {('session', 'staff')},
            },
        ),
    ]
