# Generated by Django 6.0.3 on 2026-04-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventstaff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventstaff.staffrole', verbose_name='Role'),
        ),
    ]
