# Generated by Django 5.2.13 on 2026-04-29 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0001_initial'),
        ('eventstaff', '0003_staff_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRolePermissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role_assignments', to='accesscontrol.accesspermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_assignments', to='eventstaff.staffrole')),
            ],
            options={
                'ordering': ('role__name', 'permission__code'),
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
