# Generated by Django 5.2.13 on 2026-05-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventstaff', '0005_staff_agency_services'),
        ('user', '0007_usermodel_branch_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='branch_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='user.branchprofile'),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='branch_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_roles', to='user.branchprofile'),
        ),
        migrations.AddField(
            model_name='waitertype',
            name='branch_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_types', to='user.branchprofile'),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Role Name'),
        ),
        migrations.AlterField(
            model_name='waitertype',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Waiter Type'),
        ),
    ]
