# Generated by Django 5.2.13 on 2026-05-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventstaff', '0007_assignment_response_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstaffassignmentresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
