# Generated by Django 5.2.13 on 2026-05-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_assigned', 'Event assigned'), ('event_updated', 'Event updated'), ('event_cancelled', 'Event cancelled'), ('staff_response', 'Staff response'), ('vendor_assigned', 'Vendor assigned'), ('vendor_response', 'Vendor response'), ('generic', 'Generic')], default='generic', max_length=32),
        ),
    ]
